#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# (c) Copyright 2026 Sensirion AG, Switzerland
#
#     THIS FILE IS AUTOMATICALLY GENERATED!
#
# Generator:     sensirion-driver-generator 1.7.0
# Product:       sen66
# Model-Version: 1.7.0
#

import argparse
import time
from sensirion_i2c_driver import I2cConnection, CrcCalculator
from sensirion_shdlc_driver import ShdlcSerialPort, ShdlcConnection
from sensirion_shdlc_sensorbridge import (SensorBridgePort,
                                          SensorBridgeShdlcDevice,
                                          SensorBridgeI2cProxy)
from sensirion_driver_adapters.i2c_adapter.i2c_channel import I2cChannel
from sensirion_i2c_sen66.device import Sen66Device

parser = argparse.ArgumentParser()
parser.add_argument('--serial-port', '-p', default='COM1')
args = parser.parse_args()

with ShdlcSerialPort(port=args.serial_port, baudrate=460800) as port:
    bridge = SensorBridgeShdlcDevice(ShdlcConnection(port), slave_address=0)
    bridge.set_i2c_frequency(SensorBridgePort.ONE, frequency=100e3)
    bridge.set_supply_voltage(SensorBridgePort.ONE, voltage=3.3)
    bridge.switch_supply_on(SensorBridgePort.ONE)
    i2c_transceiver = SensorBridgeI2cProxy(bridge, port=SensorBridgePort.ONE)
    channel = I2cChannel(I2cConnection(i2c_transceiver),
                         slave_address=0x6B,
                         crc=CrcCalculator(8, 0x31, 0xff, 0x0))
    sensor = Sen66Device(channel)
    try:
        sensor.stop_measurement()
        time.sleep(0.05)

    except:  # noqa
        print("stop measurement not successful"
              )

    sensor.start_continuous_measurement()
    time.sleep(1.0)
    for i in range(100):
        (padding, data_ready
         ) = sensor.get_data_ready()
        if data_ready:

            #         Readout raw data from the sensor
            (raw_humidity, raw_temperature, raw_voc, raw_nox, raw_co2
             ) = sensor.read_measured_raw_values()
            print(f"Raw humidity: {raw_humidity}"
                  )
            print(f"Raw temperature: {raw_temperature}"
                  )
            print(f"Raw VOC index: {raw_voc}"
                  )
            print(f"Raw NOX index: {raw_nox}"
                  )
            print(f"Raw CO₂: {raw_co2}"
                  )
