#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# (c) Copyright 2026 Sensirion AG, Switzerland
#
#     THIS FILE IS AUTOMATICALLY GENERATED!
#
# Generator:     sensirion-driver-generator 1.7.0
# Product:       sen66
# Model-Version: 1.7.3
#

import argparse
import time
from sensirion_i2c_driver import LinuxI2cTransceiver, I2cConnection, CrcCalculator
from sensirion_driver_adapters.i2c_adapter.i2c_channel import I2cChannel
from sensirion_i2c_sen66.device import Sen66Device

parser = argparse.ArgumentParser()
parser.add_argument('--i2c-port', '-p', default='/dev/i2c-1')
args = parser.parse_args()

with LinuxI2cTransceiver(args.i2c_port) as i2c_transceiver:
    channel = I2cChannel(I2cConnection(i2c_transceiver),
                         slave_address=0x6B,
                         crc=CrcCalculator(8, 0x31, 0xff, 0x0))
    sensor = Sen66Device(channel)
    try:
        sensor.stop_measurement()
        time.sleep(0.05)

    except:  # noqa
        print("stop measurement not successful"
              )

    #     Set the temperature acceleration parameters
    #     k = 1
    #     p = 1
    #     t1 = 1
    #     t2 = 1
    sensor.set_temperature_acceleration_parameters(1, 1, 1, 1)

    #     Start continous measurement
    sensor.start_continuous_measurement()
    time.sleep(1.0)
    for i in range(100):
        (padding, data_ready
         ) = sensor.get_data_ready()
        if data_ready:

            #         Readout data from the sensor
            (mass_concentration_pm1p0, mass_concentration_pm2p5, mass_concentration_pm4p0, mass_concentration_pm10p0,
             ambient_humidity, ambient_temperature, voc_index, nox_index, co2
             ) = sensor.read_measured_values_as_integers()
            print(f"Mass concentration pm1p0 [µg/m³]: {mass_concentration_pm1p0 / 10.0}"
                  )
            print(f"Mass concentration pm2p5 [µg/m³]: {mass_concentration_pm2p5 / 10.0}"
                  )
            print(f"Mass concentration pm4p0 [µg/m³]: {mass_concentration_pm4p0 / 10.0}"
                  )
            print(f"Mass concentration pm10p0 [µg/m³]: {mass_concentration_pm10p0 / 10.0}"
                  )
            print(f"Ambient humidity [%]: {ambient_humidity / 100.0}"
                  )
            print(f"Ambient temperature [°C]: {ambient_temperature / 200.0}"
                  )
            print(f"VOC index: {voc_index}"
                  )
            print(f"NOX index: {nox_index}"
                  )
            print(f"CO₂ [ppm]: {co2}"
                  )
