#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# (c) Copyright 2026 Sensirion AG, Switzerland
#
#     THIS FILE IS AUTOMATICALLY GENERATED!
#
# Generator:     sensirion-driver-generator 1.7.0
# Product:       sen66
# Model-Version: 1.7.1
#

import argparse
import time
from sensirion_i2c_driver import I2cConnection, CrcCalculator
from sensirion_shdlc_driver import ShdlcSerialPort, ShdlcConnection
from sensirion_shdlc_sensorbridge import (SensorBridgePort,
                                          SensorBridgeShdlcDevice,
                                          SensorBridgeI2cProxy)
from sensirion_driver_adapters.i2c_adapter.i2c_channel import I2cChannel
from sensirion_i2c_sen66.device import Sen66Device

parser = argparse.ArgumentParser()
parser.add_argument('--serial-port', '-p', default='COM1')
args = parser.parse_args()

with ShdlcSerialPort(port=args.serial_port, baudrate=460800) as port:
    bridge = SensorBridgeShdlcDevice(ShdlcConnection(port), slave_address=0)
    bridge.set_i2c_frequency(SensorBridgePort.ONE, frequency=100e3)
    bridge.set_supply_voltage(SensorBridgePort.ONE, voltage=3.3)
    bridge.switch_supply_on(SensorBridgePort.ONE)
    i2c_transceiver = SensorBridgeI2cProxy(bridge, port=SensorBridgePort.ONE)
    channel = I2cChannel(I2cConnection(i2c_transceiver),
                         slave_address=0x6B,
                         crc=CrcCalculator(8, 0x31, 0xff, 0x0))
    sensor = Sen66Device(channel)
    try:
        sensor.stop_measurement()
        time.sleep(0.05)

    except:  # noqa
        print("stop measurement not successful"
              )

    #     Set voc paramters:
    #       index_offset = 100
    #       learning_time_offset_hours = 12
    #       learning_time_gain_hours = 12
    #       gating_max_duration_minutes = 180
    #       std_initial = 50
    #       gain_factor = 230
    sensor.set_voc_algorithm_tuning_parameters(100, 12, 12, 180, 50, 230)

    #     Start continous measurement
    sensor.start_continuous_measurement()
    time.sleep(1.0)
    for i in range(100):
        (padding, data_ready
         ) = sensor.get_data_ready()
        if data_ready:

            #         Readout data from the sensor
            (mass_concentration_pm1p0, mass_concentration_pm2p5, mass_concentration_pm4p0, mass_concentration_pm10p0,
             ambient_humidity, ambient_temperature, voc_index, nox_index, co2
             ) = sensor.read_measured_values_as_integers()
            print(f"Mass concentration pm1p0 [µg/m³]: {mass_concentration_pm1p0 / 10.0}"
                  )
            print(f"Mass concentration pm2p5 [µg/m³]: {mass_concentration_pm2p5 / 10.0}"
                  )
            print(f"Mass concentration pm4p0 [µg/m³]: {mass_concentration_pm4p0 / 10.0}"
                  )
            print(f"Mass concentration pm10p0 [µg/m³]: {mass_concentration_pm10p0 / 10.0}"
                  )
            print(f"Ambient humidity [%]: {ambient_humidity / 100.0}"
                  )
            print(f"Ambient temperature [°C]: {ambient_temperature / 200.0}"
                  )
            print(f"VOC index: {voc_index}"
                  )
            print(f"NOX index: {nox_index}"
                  )
            print(f"CO₂ [ppm]: {co2}"
                  )
