#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# (c) Copyright 2026 Sensirion AG, Switzerland
#
#     THIS FILE IS AUTOMATICALLY GENERATED!
#
# Generator:     sensirion-driver-generator 1.7.0
# Product:       sen66
# Model-Version: 1.7.0
#

import argparse
import time
from sensirion_i2c_driver import LinuxI2cTransceiver, I2cConnection, CrcCalculator
from sensirion_driver_adapters.i2c_adapter.i2c_channel import I2cChannel
from sensirion_i2c_sen66.device import Sen66Device

parser = argparse.ArgumentParser()
parser.add_argument('--i2c-port', '-p', default='/dev/i2c-1')
args = parser.parse_args()

with LinuxI2cTransceiver(args.i2c_port) as i2c_transceiver:
    channel = I2cChannel(I2cConnection(i2c_transceiver),
                         slave_address=0x6B,
                         crc=CrcCalculator(8, 0x31, 0xff, 0x0))
    sensor = Sen66Device(channel)
    try:
        sensor.stop_measurement()
        time.sleep(0.05)

    except:  # noqa
        print("stop measurement not successful"
              )

    sensor.start_continuous_measurement()
    time.sleep(1.0)
    for i in range(100):
        (padding, data_ready
         ) = sensor.get_data_ready()
        if data_ready:

            #         Readout raw data from the sensor
            (raw_humidity, raw_temperature, raw_voc, raw_nox, raw_co2
             ) = sensor.read_measured_raw_values()
            print(f"Raw humidity: {raw_humidity}"
                  )
            print(f"Raw temperature: {raw_temperature}"
                  )
            print(f"Raw VOC index: {raw_voc}"
                  )
            print(f"Raw NOX index: {raw_nox}"
                  )
            print(f"Raw CO₂: {raw_co2}"
                  )
